M48
; DRILL file {KiCad (6.0.8-1)-1} date Tuesday, November 22, 2022 at 09:58:46 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-22T09:58:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X3.2087Y-3.2331
X4.6256Y-2.4085
X4.6256Y-4.045
T0
M30
