M48
; DRILL file {KiCad (6.0.7-1)-1} date Sunday, January 08, 2023 at 04:55:36 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-08T16:55:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X120.85Y-104.56
X156.84Y-125.275
X156.85Y-83.75
T0
M30
