M48
; DRILL file {KiCad (6.0.7-1)-1} date Thursday, November 03, 2022 at 05:34:57 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-03T17:34:57-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X77.6Y-76.2
X113.6Y-55.415
X113.6Y-96.985
T0
M30
